"""
src/haagent/runtime/events/__init__.py - Runtime 事件协议包

集中放置 runtime 对外输出的事件协议与事件适配器。
"""

from haagent.runtime.events.bus import (
    AssistantAttemptResetBusEvent,
    AssistantDeltaBusEvent,
    AssistantIntermediateBusEvent,
    AssistantMessageBusEvent,
    LegacyRawBusEvent,
    ModelContextUsageBusEvent,
    ModelRetryExhaustedBusEvent,
    ModelRetryScheduledBusEvent,
    RuntimeBusEvent,
    ToolFailedBusEvent,
    ToolFinishedBusEvent,
    ToolStartedBusEvent,
    bus_event_from_dict,
    bus_event_to_dict,
    coerce_bus_event,
)
from haagent.runtime.events.factories import (
    failure_notice_event,
    memory_candidates_created_event,
    memory_extraction_warning_event,
    session_lifecycle_event,
)
from haagent.runtime.events.registry import RAW_RUNTIME_UI_EVENT_REGISTRY, RawRuntimeUiEventSpec
from haagent.runtime.events.types import (
    RUNTIME_UI_EVENT_TYPES,
    ApprovalStateEvent,
    AssistantAttemptResetEvent,
    AssistantDeltaEvent,
    AssistantIntermediateEvent,
    AssistantMessageEvent,
    ContextUsageEvent,
    FailureNoticeEvent,
    MemoryNoticeEvent,
    RuntimeUiEvent,
    RuntimeUiEventType,
    SessionLifecycleEvent,
    TaskProgressEvent,
    ToolActivityEvent,
    UserInputStateEvent,
    WarningNoticeEvent,
)
from haagent.runtime.events.ui_mapper import RuntimeUiEventMapper

__all__ = [
    "AssistantAttemptResetBusEvent",
    "AssistantDeltaBusEvent",
    "AssistantIntermediateBusEvent",
    "AssistantMessageBusEvent",
    "LegacyRawBusEvent",
    "ModelContextUsageBusEvent",
    "ModelRetryExhaustedBusEvent",
    "ModelRetryScheduledBusEvent",
    "RAW_RUNTIME_UI_EVENT_REGISTRY",
    "RUNTIME_UI_EVENT_TYPES",
    "ApprovalStateEvent",
    "AssistantAttemptResetEvent",
    "AssistantDeltaEvent",
    "AssistantIntermediateEvent",
    "AssistantMessageEvent",
    "ContextUsageEvent",
    "FailureNoticeEvent",
    "MemoryNoticeEvent",
    "RawRuntimeUiEventSpec",
    "RuntimeBusEvent",
    "RuntimeUiEvent",
    "RuntimeUiEventMapper",
    "RuntimeUiEventType",
    "SessionLifecycleEvent",
    "TaskProgressEvent",
    "ToolActivityEvent",
    "ToolFailedBusEvent",
    "ToolFinishedBusEvent",
    "ToolStartedBusEvent",
    "UserInputStateEvent",
    "WarningNoticeEvent",
    "bus_event_from_dict",
    "bus_event_to_dict",
    "coerce_bus_event",
    "failure_notice_event",
    "memory_candidates_created_event",
    "memory_extraction_warning_event",
    "session_lifecycle_event",
]
